var login = document.getElementsByClassName("login")
var email = document.getElementsByClassName("email")
var password = document.getElementsByClassName("password")
var error = document.getElementById ("error")
var input = document.getElementById ("password")
var inputwo = document.getElementById("email")
var label = document.getElementById ("password")
var labeltwo = document.getElementById ("email")