var emailValidation = document.getElementById("form-email")
var passwordValidation = document.getElementById("form-password")
var formValidation = document.getElementsByClassName("form")
var labelValidation = document.getElementsByClassName("label")
var inputValidation = document.getElementsByClassName("input")
var buttonValidation = document.getElementsByTagName("button")
var error = document.getElementById("error")